#!/usr/bin/env python3
import subprocess
import json
import time
import sys
from llm_analyzer import LLMAnalyzer
from spiderfoot_extractor import SpiderFootExtractor

class ReconPipeline:
    def __init__(self):
        self.analyzer = LLMAnalyzer()
        self.extractor = SpiderFootExtractor()
    
    def run_spiderfoot_scan(self, target, modules="sfp_dnsresolve,sfp_whois,sfp_subdomain_enum"):
        print(f"Starting SpiderFoot scan for: {target}")
        cmd = [
            "python3", "/opt/spiderfoot/sf.py",
            "-s", target,
            "-t", "DOMAIN_NAME",
            "-m", modules,
            "-q"
        ]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            if result.returncode == 0:
                print("SpiderFoot scan completed successfully")
                return True
            else:
                print(f"SpiderFoot scan failed: {result.stderr}")
                return False
        except subprocess.TimeoutExpired:
            print("SpiderFoot scan timed out")
            return False
    
    def analyze_results(self):
        print("Extracting SpiderFoot results...")
        time.sleep(5)  # Allow database to update
        
        summary = self.extractor.get_latest_scan_summary()
        if "error" in summary:
            print(f"Error extracting data: {summary['error']}")
            return None
        
        print("Analyzing results with LLM...")
        analysis_data = json.dumps(summary)
        
        # Get different types of analysis
        threat_analysis = self.analyzer.analyze_osint_data(analysis_data, "threats")
        recommendations = self.analyzer.analyze_osint_data(analysis_data, "recommendations")
        
        return {
            "raw_summary": summary,
            "threat_analysis": threat_analysis,
            "recommendations": recommendations
        }
    
    def generate_report(self, target, analysis):
        report = f"""
# AI-Powered Reconnaissance Report for {target}

## Raw Data Summary
- Total Findings: {analysis['raw_summary']['total_findings']}
- Domains Found: {len(analysis['raw_summary']['domains'])}
- IP Addresses: {len(analysis['raw_summary']['ips'])}
- Email Addresses: {len(analysis['raw_summary']['emails'])}

## AI Threat Analysis
{analysis['threat_analysis']}

## AI Security Recommendations
{analysis['recommendations']}

Generated by AI-Powered Reconnaissance Pipeline
"""
        
        filename = f"recon_report_{target.replace('.', '_')}.md"
        with open(filename, 'w') as f:
            f.write(report)
        
        print(f"Report saved to: {filename}")
        return filename

def main():
    if len(sys.argv) != 2:
        print("Usage: python3 recon_pipeline.py <target_domain>")
        sys.exit(1)
    
    target = sys.argv[1]
    pipeline = ReconPipeline()
    
    # Run the complete pipeline
    if pipeline.run_spiderfoot_scan(target):
        analysis = pipeline.analyze_results()
        if analysis:
            pipeline.generate_report(target, analysis)
            print("Reconnaissance pipeline completed successfully!")
        else:
            print("Failed to analyze results")
    else:
        print("Failed to run SpiderFoot scan")

if __name__ == "__main__":
    main()
